---
title: "p8105_hw1_zf2211"
author: "Francis"
date: "9/21/2018"
output: github_document
---

# Problem 1

```{r data frame}
library(tidyverse)
sed.seed = 777
rs = runif(10, 0, 5)
df = tibble(
  rs,
  vec_logical = rs>2,
  vec_character = c("usa", "canada", "france", "england", "japan", "sweden", "korea", "germany", "italy", "austria"),
  vec_factor = c("M", "M", "M", "F", "M", "F", "M", "F", "M", "F")
)
#print df
df
#mean of variables in dataframe
mean(df$rs)
mean(df$vec_logical)
mean(df$vec_character)
mean(df$vec_factor)
###We can calculate numeric and logical vectors' means because the logical vector "FALSE" and "TRUE" was transformed into numeric 0 and 1. Since character and factor cannot be transformed, their means could not be calculated.

```

```{r convert variables}
as.numeric(df$vec_logical)
as.numeric(df$vec_character)
as.numeric(df$vec_factor)
###It shows logical "TRUE" and "FALSE" could be converted into numeric 1 and 0, while character and factor variables could not be converted (respectively replaced by "NA" after coercion).
```

```{r two step convert}
as.numeric(
  as.factor(df$vec_character)
)
as.numeric(
  as.character(df$vec_factor)
)
###If I convert character to factor then numeric, it will work. It seems those characters refer to data in some database? While converting factor to character then numeric doesn't work (respectively replaced by "NA" after coercion).
```

# Problem 2

```{r data frame 2}
set.seed(777)

x = rnorm(1000)
y = rnorm(1000)
vec_logical2 = x + y > 0
vec_numeric2 = as.numeric(vec_logical2)
vec_factor2 = as.factor(vec_logical2)

df2 = tibble(x, y, vec_logical2, vec_numeric2, vec_factor2)

df2
```

the size of the dataset is `r nrow(df2)` rows * `r ncol(df2)` columes.
the mean and median of x is `r mean(x)` and `r median(x)`.
the proportion of cases for which the logical vector is TRUE is `r sum(vec_logical2)/length(vec_logical2)`).

```{r scatterplot}
library(ggplot2)
ggplot(df2, aes(x = x, y = y, color = vec_logical2)) + geom_point()
ggsave("df2.pdf", height = 5, width = 7 )
###save the graph as df2.pdf, let the height be 5, width be 7.
ggplot(df2, aes(x = x, y = y, color = vec_numeric2)) + geom_point()
ggplot(df2, aes(x = x, y = y, color = vec_factor2)) + geom_point()

###From the color scales we can see that the color of the dots in first(logical vector) and third(factor vector) is bipolar, while the second(numeric vector) is gradual.
```

